### ISSUE TITLE
Clarification of license

### ISSUE THREAD

**Issue by Earthcomputer** [MinecraftModDevelopmentMods/MOPM#14]
Hi, the curseforge page for this mod states that this mod is GPL, however the LICENSE-new file in this repository says LGPL. Which is it? Thanks :)

**Comment by zedlander1000** [comment]
Sorry it has taken me so long to respond. I was meaning to get around to this, and I have. Thanks for pointing out the inconsistency. The license on the Github page should now be GPL v3. I'm going to make sure that still matches with the Curseforge project.
